# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('numb', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
